apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
  namespace: voting-proj
spec:
  type: ClusterIP
  ports:
  - name: "result-service"
    port: 80
    targetPort: 80
  selector:
    app: result
